### PR TITLE
Possible typo?

### PR DESCRIPTION
**Pull request by rickyeh**
If you're still maintaining this... think I found a typo. Don't ask me how I found this.... :(

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by kaesonho** [comment]
that's definitely a typo 😰    thanks for fixing this!

**Comment by kaesonho** [comment]
👍

**Comment by kaesonho** [comment]
it's published :) https://github.com/yahoo/subscribe-ui-event/releases/tag/v1.0.13

**Comment by roderickhsiao** [comment]
Thanks for catching!

**Pull request merged**
