### PR TITLE
Use libraries directly from lodash

### LINKED ISSUE #25: Use lodash instead of individual lodash packages
@hankhsiao @roderickhsiao 

Its better to just require lodash and then change the require to target the library needed. Right now, with [lodash.clone](https://github.com/yahoo/subscribe-ui-event/blob/master/package.json#L28) pulled in as a separate package, it introduces duplicate clone libraries bundled to the client (assuming another library is pulling in lodash).

### PR DESCRIPTION
**Pull request by redonkulus**
@hankhsiao @roderickhsiao 

Fixes #25

### CODE REVIEW

**Comment by roderickhsiao** [comment]
:+1:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
@roderickhsiao want to merge and publish?

**Comment by roderickhsiao** [comment]
no access, probably need to wait @hankhsiao

**Comment by hankhsiao** [comment]
:+1:

**Comment by redonkulus** [comment]
@hankhsiao can you please add me as owner for the npm package?

**Pull request merged**
