### PR TITLE
chore: update raf

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
More tree shaking, keeping it up to date

### CODE REVIEW

**Comment by redonkulus** [comment]
@ScriptedAlchemy can you check why the build failed?

**Comment by ScriptedAlchemy** [comment]
Will do, gimme some time tho :)

**Comment by ScriptedAlchemy** [comment]
Checking it out, fails on this

```
Running "connect:functional" (connect) task
Started connect web server on http://localhost:9999
Running "saucelabs-mocha:all" (saucelabs-mocha) task
=> Starting Tunnel to Sauce Labs
>> 
=> Stopping Tunnel to Sauce Labs
>> Error closing tunnel
```

Going to reinstall 3.0.0 and see if that makes any difference, otherwise, do you open and tunnels to a saucelabs service?

**Comment by redonkulus** [comment]
@ScriptedAlchemy that’s correct. We use saucelabs for functional tests. I haven’t seen that error before. @roderickhsiao any clue?

**Comment by tinder-rhsiao** [comment]
Probably the api key?

**Comment by roderickhsiao** [comment]
@redonkulus Seems something has changed for saucelab connect, currently I apply an account for both `react-i13n` and `subscribe-ui-event`, the last activity from saucelab dashboard is June 24, and after that I didn't see any activity being run at that account.

Do you want to use this chance to migrate to some other testing platform? I notice formatjs is using Karma.

**Comment by redonkulus** [comment]
Ya I’m fine with that.

**Comment by ScriptedAlchemy** [comment]
Okay let me re-update raf again. Will do tonight. On a boat with the family

**Comment by ScriptedAlchemy** [comment]
Okay, re-updated it :)

**Comment by tinder-rhsiao** [comment]
the build probably won't pass still due to the functional test for sauce lab. I could try to find sometime this week or next week to check it, but that shouldn't block this though.

**Comment by ScriptedAlchemy** [comment]
Just updating the code so if someone can / knows sauce, its here and ready . <3

**Comment by ScriptedAlchemy** [comment]
Bump

**Comment by roderickhsiao** [comment]
This should be safe to merge, but @ScriptedAlchemy just curious if you installed the current version, it should be able to download the latest version of `raf` for the matched semver, do we need to force. upgrade here (usually for security reason we want to force the version)

**Pull request closed without merging**
