### PR TITLE
Add support for selectionchange event on document

### PR DESCRIPTION
**Pull request by kmck**
Noticed that this event wasn't supported already, so I added it.

@roderickhsiao

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by hankhsiao** [comment]
Hesitate to add this one because it is not necessary. All events here are globally affected, for example, scroll, resize. Once they get triggered, a lot of callbacks may run. However, selectionchange usually affects only an element. So not over-designing it may be more performant. Does it make sense?

**Comment by roderickhsiao** [comment]
I think the problem is `selectionchange` can only listens on the top scope 
https://developer.mozilla.org/en-US/docs/Web/Events/selectionchange

and need to nastily filter based on the selection, thats why having a high level registration might make sense?

**Comment by kmck** [comment]
how are we feeling about this?

**Comment by roderickhsiao** [comment]
I discussed with @hankhsiao over weekend, and thinking perhaps we could have a public method or something to register custom event to the connector then we don't need to keep adding different event later. How do you think?

This PR is fine for me but just not sure should we just go for adding new support for all custom event or just this one.

**Comment by hankhsiao** [comment]
@kmck do you think you can write a function for registering new event?

**Comment by kmck** [comment]
i think that expands the scope beyond what i'm concerned with...

if you expose `connectDiscreteEvent`, it starts to make sense to remove event registration altogether, add a `target` argument to the `subscribe` and `unsubscribe` functions, and let the library figure out whether an target/event combo needs a new emitter. at that point, it's practically a new library 😄

**Comment by redonkulus** [comment]
Going to close this since the original implementation is not agreed upon. Feel free to discuss further if a new PR is warranted.

**Pull request closed without merging**
